title: Lucas Eloi # your name (or website title) here
logo: "/images/linkedin.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Engenheiro de Dados com experiência em desenvolver e otimizar pipelines robustos, garantindo qualidade e suporte a iniciativas de analytics e business intelligence. Utilizo SQL, Python e tecnologias cloud para criar arquiteturas escaláveis que impulsionam decisões inteligentes e eficiência operacional. Meu trabalho conecta dados brutos a insights acionáveis, entregando informações confiáveis e bem estruturadas para equipes multidisciplinares.
  <br><br>
  <a href="https://www.linkedin.com/in/lucaseloi1/">View my LinkedIn Profile</a> 
  <br><br>
  <br><br>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
